class CasioTranslator {
  static const Map<String, String> _dictionary = {
    "Simultaneous Equation with 2 Unknowns": "Phương trình tuyến tính đồng thời với 2 ẩn",
    "Simultaneous Equation with 3 Unknowns": "Phương trình tuyến tính đồng thời với 3 ẩn",
    "Simultaneous Equation with 4 Unknowns": "Phương trình tuyến tính đồng thời với 4 ẩn",
    "Quadratic Equation [ax²+bx+c=0]": "Phương trình bậc hai [ax²+bx+c=0]",
    "Cubic Equation [ax³+bx²+cx+d=0]": "Phương trình bậc hai [ax³+bx²+cx+d=0]",
    "Quartic Equation [ax⁴+bx³+cx²+dx+e=0]": "Phương trình bậc bốn [ax⁴+bx³+cx²+dx+e=0]",
    "Normal Probability Density": "Mật độ xác suất chuẩn",
    "Normal Cumulative Distribution": "Phân phối tích lũy chuẩn",
    "Inverse Normal Cumulative Distribution": "Phân phối tích lũy chuẩn nghịch đảo",
    "Binomial Cumulative Distribution": "Phân phối tích lũy nhị thức",
    "Poisson Cumulative Distribution": "Phân phối tích lũy Poisson",
    "Calculate Manual": "HDSD Phép tính thường",
    "Base-N Manual": "HDSD Hệ đếm cơ số N",
    "Statistics Manual": "HDSD Thống kê",
    "Complex Manual": "HDSD Số phức",
    "Equation Manual": "HDSD Phương trình",
    "Matrix Manual": "HDSD Ma trận",
    "Vector Manual": "HDSD Véc-tơ",
    "Table Manual": "HDSD Bảng giá trị",
    "Verify Manual": "HDSD Kiểm chứng",
    "Graph Manual": "HDSD Kiểm chứng",
    "Ratio Manual": "HDSD Tỉ lệ thức",
    "Inequality Manual": "HDSD Bất phương trình",
    "Distribution Manual": "HDSD Phân phối",
    "Spreadsheet Manual": "HDSD Bảng tính",
    "Algorithm Manual": "HDSD Thuật toán",
    "Math Box Manual": "HDSD Hộp toán học",
    "Setup Menu Manual": "HDSD Trình cài đặt",
    "Setup Sub Menu Manual": "HDSD Trình cài đặt (phụ)",
    "Equation Complex Root": "Nghiệm Phức Phương trình",
    "Spreadsheet: Auto Calc": "Bảng tính: Tự động tính",
    "Spreadsheet: Show Cell": "Bảng tính: Hiện ô",
    "Algorithm: Background": "Thuật toán: Nền",
    "Algorithm: Unit Setting": "Thuật toán: Cài đặt đơn vị",
    "Linear Regression": "Hồi quy tuyến tính",
    "Quadratic Regression": "Hồi quy bậc hai",
    "Logarithmic Regression": "Hồi quy lôgarit",
    "e exponential Regression": "e hồi quy hàm số mũ",
    "ab exponential Regression": "ab hồi quy hàm số mũ",
    "Power Regression": "Hồi quy lũy thừa",
    "Inverse Regression": "Hồi quy nghịch đảo",
    "Binomial Probability": "Xác suất nhị thức",
    "Poisson Probability": "Xác suất Poisson",
    "Single-Variable Statistic": "Thống kê 1 biến",
    "MathI/DecimalO": "Số tự nhiên vào/Số thập phân ra",
    "LineI/DecimalO": "Dòng vào/Số thập phân ra",
    "Fraction Result": "Kết quả phân số",
    "Complex Result": "Kết quả số phức",
    "Statistics Frequency": "Tần số thống kê",
    "Recurring Decimal": "Số thập phân tuần hoàn",
    "Auto Power Off": "Tự động tắt",
    "Engineer Symbol": "Kí hiệu kĩ thuật",
    "Digit Separator": "Dấu cách 3 chữ số",
    "Multi-Line Font": "Phông Multi-Line",
    "QR Code Version": "Phiên bản mã QR",
    "All Real Numbers": "Tất cả số thực",
    "Infinite Solution": "Vô số nghiệm",
    "No Real Roots": "Vô nghiệm",
    "No Local Max/Min": "Không có CĐ/CT",
    "MathI/MathO": "Số tự nhiên vào/ra",
    "LineI/LineO": "Dòng vào/ra",
    "Number Format": "Định dạng số",
    "Decimal Mark": "Dấu thập phân",
    "Angle Unit": "Đơn vị góc",
    "Table Type": "Loại bảng",
    "Small Font": "Phông chữ nhỏ",
    "Normal Font": "Phông chữ thường",
    "Version 3": "Phiên bản 3",
    "Version 11": "Phiên bản 11",
    "Equation": "Phương trình",
    "Table": "Bảng giá trị",
    "Verify": "Kiểm chứng",
    "Solver": "Bộ giải phương trình",
    "Calculate": "Phép tính thường",
    "Base-N": "Hệ đếm cơ số N",
    "Binary": "Nhị phân",
    "Octal": "Bát phân",
    "Decimal": "Thập phân",
    "Hexadecimal": "Thập lục phân",
    "Statistics": "Thống kê",
    "Complex": "Số phức",
    "Matrix": "Ma trận",
    "Vector": "Véc-tơ",
    "Ratio": "Tỉ lệ thức",
    "Inequality": "Bất phương trình",
    "Distribution": "Phân phối",
    "Spreadsheet": "Bảng tính",
    "Algorithm": "Thuật toán",
    "Math Box": "Hộp Toán học",
    "AC Break": "Ngắt AC",
    "Syntax ERROR": "Lỗi cú pháp",
    "Math ERROR": "Lỗi phép tính",
    "Range ERROR": "Lỗi phạm vi",
    "Cannot Simplify": "Không thể rút gọn",
    "Circular ERROR": "Lỗi vòng lặp",
    "Stack ERROR": "Lỗi nhóm phép tính",
    "Argument ERROR": "Lỗi đối số",
    "Dimension ERROR": "Lỗi kích thước",
    "Cannot Solve": "Không giải được",
    "Time Out": "Hết thời gian",
    "Variable ERROR": "Lỗi biến số",
    "NULL ERROR": "Lỗi NULL",
    "Memory ERROR": "Lỗi bộ nhớ",
    "No Operator": "Không có Toán tử",
    "Not Defined": "Không xác định",
    "Nesting ERROR": "Lỗi lồng hàm",
    "Norm1": "Viết số bình thường 1",
    "Norm2": "Viết số bình thường 2",
    "Fix": "Chọn số thập phân",
    "Sci": "Dạng a×10ⁿ",
    "Comma": "Phẩy",
    "Dot": "Chấm",
    "Degree": "Độ",
    "Radian": "Radian",
    "Gradian": "Grad",
    "Off": "Tắt",
    "On": "Bật",
    "Auto": "Tự động",
    "Manual": "Bằng tay",
    "Simplify": "Rút gọn",
    "10 Min.": "10 phút",
    "60 Min.": "60 phút",
    "Formula": "Công thức",
    "Value": "Giá trị",
    "Axes/Grid": "Trục/Lưới",
    "Axes/xy": "Trục/xy",
    "Axes": "Trục",
    "None": "Không có",
    "pixels": "pixel",
    "units": "đơn vị",
    "Lower=\${0}": "Ldưới=\${0}",
    "Upper=\${1}": "Ltrên=\${1}",
    "Area=\${0}": "Vùng=\${0}",
    "No Solution": "Vô nghiệm",
  };

  // Tạo một list keys đã được sắp xếp theo ĐỘ DÀI GIẢM DẦN.
  // Khởi tạo 1 lần duy nhất để tiết kiệm tài nguyên.
  static final List<String> _sortedKeys = _dictionary.keys.toList()
    ..sort((a, b) => b.length.compareTo(a.length));

  /// Hàm dịch: Quét toàn bộ từ điển và thay thế chuỗi tiếng Anh bằng tiếng Việt
  static String translate(String input) {
    if (input.isEmpty) return input;

    String result = input;

    // Lặp qua danh sách từ khóa (từ dài nhất đến ngắn nhất)
    for (String key in _sortedKeys) {
      if (result.contains(key)) {
        // Thay thế tất cả các chỗ xuất hiện của từ khóa tiếng Anh
        result = result.replaceAll(key, _dictionary[key]!);
      }
    }

    return result;
  }
}
